apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-yqxh
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-yqxh
    app.kubernetes.io/part-of: tkwch-fix-0075-0010-app
  name: devfile-sample-yqxh
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-yqxh
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-yqxh
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0010-tenant/tkwch-fix-0075-0010-app/devfile-sample-yqxh@sha256:28b0a516fb1793110dd4a0b3ad30fcedcc51fda93a6a9ebd4951deb0203b21b3
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
